name = "iplc-ai"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[ai]
binding = "AI"

[[vectorize]]
binding    = "DOC_INDEX"         # matches dashboard
index_name = "iplc-chat-index"

[[kv_namespaces]]
binding    = "DOC_METADATA"
id         = "bcb326be651d44e98eb4d220003d6473"
preview_id = "053128e230ce47f7b01e2f17dcaf2547"

[[kv_namespaces]]
binding    = "SESSION"
id         = "a4926bc00e9b438a898289934457a579"

[[durable_objects.bindings]]
name       = "AI_GATE"
class_name = "AIGate"

[[migrations]]
tag = "v3-aigate-sqlite"
new_sqlite_classes = ["AIGate"]   # required on free tier