name = "iplc-ai"
main = "src/index.ts"
compatibility_date = "2025-04-01"

# AI binding configuration
[ai]
binding = "AI"

# Vectorize configuration for document embeddings
[[vectorize]]
binding = "DOC_INDEX"
index_name = "iplc-chat-index"

# KV namespace for document metadata
[[kv_namespaces]]
binding = "DOC_METADATA"
id = "DOC_METADATA_ID_PLACEHOLDER"
preview_id = "DOC_METADATA_ID_PLACEHOLDER"

# Durable Objects for session management
[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDO"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = [ "SessionDO" ]

# Cron triggers for scheduled cleanup
[triggers]
crons = ["0 2 * * *"]  # Run daily at 2 AM UTC

# Environment specific settings
[env.development]
vars = { }