name = "iplcforms-v3"
main = "src/index.ts"
compatibility_date = "2024-03-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Service binding to iplc-ai worker
[[services]]
binding = "IPLC_AI"
service = "iplc-ai"

# AI binding for Workers AI (keep for backward compatibility)
[ai]
binding = "AI"

# Vectorize index for document embeddings (keep for backward compatibility)
[[vectorize]]
binding = "DOC_INDEX"
index_name = "doc-index"

# KV namespaces for data storage
[[kv_namespaces]]
binding = "USER_SESSIONS"
id = "92ec4b43378242efaad5c898e961f8981"
preview_id = "92ec4b43378242efaad5c898e961f8981"

[[kv_namespaces]]
binding = "DOCUMENTS"
id = "995f435153f84382a70fff8ab3a8e892"
preview_id = "995f435153f84382a70fff8ab3a8e892"

[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "30dd285e5d5a4cabafbd9fae69ba5d5e"
preview_id = "30dd285e5d5a4cabafbd9fae69ba5d5e"

[[kv_namespaces]]
binding = "SESSION"
id = "a4926bc00e9b438a898289934457a579"
preview_id = "a4926bc00e9b438a898289934457a579"

# Durable Objects configuration
[[durable_objects.bindings]]
name = "AI_GATE"
class_name = "AIGate"

[[durable_objects.bindings]]
name = "FORM_SESSION"
class_name = "FormSessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AIGate", "FormSessionDO"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "admin-db"
database_id = "ef0966c1-4e6b-40a3-bdd2-57fe48ad3b3a"